[workspace]
members = [
    "crates/models",
    "crates/tree_ops",
    "crates/database",
    "crates/scanner",
    "crates/utils",
    "crates/views",
    "crates/storage-wars",
]
resolver = "2"

[workspace.dependencies]
models = { path = "crates/models" }
tree_ops = { path = "crates/tree_ops" }
database = { path = "crates/database" }
scanner = { path = "crates/scanner" }
utils = { path = "crates/utils" }
views = { path = "crates/views" }
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui" }
rusqlite = { version = "0.31", features = ["bundled"] }
sysinfo = "0.30"
chrono = "0.4"