[package]
name = "storage-wars"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "storage-wars"
path = "src/main.rs"

[dependencies]
views = { path = "../views" }
models = { path = "../models" }
database = { path = "../database" }
tree_ops = { path = "../tree_ops" }
scanner = { path = "../scanner" }
utils = { path = "../utils" }
gpui = "0.1.0"